import { chromium, Page } from 'playwright';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_DIR = path.resolve(__dirname, '../output/local-sites');

const SITES = {
  news_homepage: [
    'https://www.bbc.com/',
    'https://www.cnn.com/',
  ],
  ecommerce_product: [
    'https://www.amazon.com/dp/B09G3HRMVB',
    'https://www.ebay.com/itm/284915742898',
  ],
  gov_form: [
    'https://www.irs.gov/forms-pubs/about-form-1040',
    'https://www.irs.gov/forms-pubs',
  ],
  dashboard: [
    'https://analytics.usa.gov/',
    'https://www.coingecko.com/',
  ],
};

const VIEWPORT = { width: 1280, height: 900 };
const TIMEOUT = 30000;
const RETRIES = 1;

interface MetaData {
  url: string;
  title: string;
  snapshot_key: string;
  timestamp: string;
  width: number;
  height: number;
  failure_reason?: string;
}

async function sanitizeHtml(page: Page): Promise<string> {
    return await page.evaluate(() => {
        const removeTags = ['script', 'style', 'iframe', 'object', 'embed'];
        removeTags.forEach(tag => {
            document.querySelectorAll(tag).forEach(el => el.remove());
        });

        const allElements = document.querySelectorAll('*');
        allElements.forEach(el => {
            Array.from(el.attributes).forEach(attr => {
                if (attr.name.startsWith('on') || attr.value.startsWith('javascript:')) {
                    el.removeAttribute(attr.name);
                }
            });
        });

        return document.documentElement.outerHTML;
    });
}

async function processUrl(category: string, url: string, browser: any) {
    const siteId = new URL(url).hostname.replace(/^www\./, '').replace(/\./g, '_');
    const siteDir = path.join(OUTPUT_DIR, category, siteId);
    
    // Create directory
    fs.mkdirSync(siteDir, { recursive: true });

    const context = await browser.newContext({ viewport: VIEWPORT });
    const page = await context.newPage();
    
    let title = '';
    let success = false;
    let finalHtml = '';
    
    for (let attempt = 0; attempt <= RETRIES; attempt++) {
        try {
            console.log(` Visiting ${url} (Attempt ${attempt + 1}/${RETRIES + 1})`);
            
            // Navigate with fallback
            try {
                await page.goto(url, { waitUntil: 'networkidle', timeout: TIMEOUT });
            } catch (e) {
                console.log('   Networkidle timeout, waiting for domcontentloaded...');
                await page.waitForLoadState('domcontentloaded', { timeout: TIMEOUT });
            }
            
            title = await page.title();
            
            // a11y
            try {
                const a11ySnapshot = await page.accessibility.snapshot();
                fs.writeFileSync(path.join(siteDir, 'a11y.json'), JSON.stringify(a11ySnapshot, null, 2));
            } catch (e) {
                console.warn(`  Failed to capture a11y for ${url}`);
            }

            // Sanitized HTML
            const html = await sanitizeHtml(page);
            finalHtml = html.substring(0, 50000);
            fs.writeFileSync(path.join(siteDir, 'rendered.html'), finalHtml);

            // Screenshot
            await page.screenshot({ path: path.join(siteDir, 'screenshot_full.png'), fullPage: true });

            success = true;
            break;
        } catch (e) {
            console.error(`  Error processing ${url}: ${e}`);
        }
    }

    if (!success && !finalHtml) {
        // Capture partial if failed
        try {
             const html = await page.content(); // simple content
             finalHtml = html.substring(0, 50000);
             fs.writeFileSync(path.join(siteDir, 'rendered.html'), finalHtml);
        } catch (e) {}
    }

    const meta: MetaData = {
        url,
        title: title || 'Unknown',
        snapshot_key: `${category}/${siteId}`,
        timestamp: new Date().toISOString(),
        width: VIEWPORT.width,
        height: VIEWPORT.height,
    };
    if (!success) meta.failure_reason = 'Navigation/Timeout failed after retries';

    fs.writeFileSync(path.join(siteDir, 'meta.json'), JSON.stringify(meta, null, 2));

    await context.close();
    return success;
}

async function run() {
    const browser = await chromium.launch();
    const summary = { pages_captured: 0, partial_failures: [] as string[], notes: 'Generated by Playwright script' };
    
    try {
        for (const [category, urls] of Object.entries(SITES)) {
            for (const url of urls) {
                const success = await processUrl(category, url, browser);
                if (success) {
                    summary.pages_captured++;
                } else {
                    summary.partial_failures.push(url);
                }
            }
        }
        
        fs.writeFileSync(path.join(OUTPUT_DIR, 'summary.json'), JSON.stringify(summary, null, 2));
        console.log('Done. Summary written to', path.join(OUTPUT_DIR, 'summary.json'));
    } finally {
        await browser.close();
    }
}

run();
